# Deploys the pmem-csi driver onto exactly one node, running in unified mode.
# That CSI driver gets exposed with a NodePort service.

apiVersion: v1
kind: Service
metadata:
  name: pmem-unified
spec:
  type: NodePort
  selector:
    app: pmem-csi-unified
  ports:
  - port: 10000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pmem-csi-unified
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pmem-csi-unified
  serviceName: pmem-csi-unified
  template:
    metadata:
      labels:
        app: pmem-csi-unified
    spec:
      initContainers:
      containers:
      - name: pmem-driver
        image: 192.168.8.1:5000/pmem-csi-driver:canary
        imagePullPolicy: Always
        # Passing /dev to container may cause container creation error because termination-log is located on /dev/ by default.
        # Adding this clause works around failure, although it's bogus as this file is not actually used.
        terminationMessagePath: /tmp/termination-log
        args:  [ "-v=5",
                 "-drivername=pmem-csi.intel.com",
                 "-mode=unified",
                 "-deviceManager=ndctl",
                 "-endpoint=$(CSI_ENDPOINT)",
                 "-nodeid=$(KUBE_NODE_NAME)" ]
        env:
        - name: CSI_ENDPOINT
          value: "tcp://0.0.0.0:10000"
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        securityContext:
          privileged: true
        volumeMounts:
          # We create temporary staging and target directories under /var/tmp
          # during csi-sanity testing and must have those visible inside the
          # container (see test/e2e/storage/sanity.go).
          - name: var-tmp
            mountPath: /var/tmp
          - name: dev-dir
            mountPath: /dev
          - name: sys-dir
            mountPath: /sys
      volumes:
        - name: var-tmp
          hostPath:
            path: /var/tmp
            type: DirectoryOrCreate
        - name: dev-dir
          hostPath:
            path: /dev
            type: DirectoryOrCreate
        - name: sys-dir
          hostPath:
            path: /sys
            type: DirectoryOrCreate
