apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pmem-csi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: pmem-csi-sc # defined in pmem-csi.yaml
