apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pmem-csi-pvc-cache
spec:
  accessModes:
  - ReadWriteMany # cache volumes are multi-node volumes
  resources:
    requests:
      storage: 8Gi
  storageClassName: pmem-csi-sc-cache # defined in pmem-storageclass-cache.yaml
