apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pmem-csi-pvc-late-binding
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: pmem-csi-sc-late-binding

