bases:
- ../kubernetes-base-direct-testing/

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: pmem-csi-intel-com-controller
  path: ../testing/controller-coverage-patch.yaml

- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: pmem-csi-intel-com-node
  path: ../testing/node-coverage-patch.yaml

images:
- name: intel/pmem-csi-driver
  newName: intel/pmem-csi-driver-test
