#!/bin/bash -eu
# Run this as root to start PMEM-CSI driver as singlehost
# drivermode=Unified
# devicemode=lvm
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
$DIR/../_output/pmem-ns-init
$DIR/../_output/pmem-vgm
_commonargs="-v 5 --endpoint tcp://127.0.0.1:10000"
_specargs="-deviceManager lvm"
$DIR/../_output/pmem-csi-driver ${_commonargs} ${_specargs}
