bases:
- ../kubernetes-base-lvm/
- ../testing/

commonLabels:
  pmem-csi.intel.com/deployment: lvm-testing

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: pmem-csi-intel-com-controller
  path: ../testing/controller-verbosity-patch.yaml

- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: pmem-csi-intel-com-node
  path: ../testing/node-verbosity-patch.yaml
