bases:
- ../kubernetes-1.14-lvm/
- ../testing/

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: pmem-csi-controller
  path: ../testing/controller-socat-patch.yaml

- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: pmem-csi-controller
  path: ../testing/args-two-containers-patch.yaml

- target:
    group: apps
    version: v1beta2
    kind: DaemonSet
    name: pmem-csi-node
  path: ../testing/args-two-containers-patch.yaml

- target:
    group: apps
    version: v1beta2
    kind: DaemonSet
    name: pmem-csi-node
  path: ../testing/args-two-initcontainers-patch.yaml
