apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: pmem-csi.intel.com
spec:
  attachRequired: false
  podInfoOnMount: true
  storageCapacity: true # beta in 1.21, GA in 1.23
  volumeLifecycleModes:
  - Persistent
  - Ephemeral
