bases:
- ../driver
- rbac

resources:
- driverinfo-beta.yaml

# The RBAC files must match the image versions.
# The sidecar versions must be kept in sync with the
# operator defaults in pkg/apis/pmemcsi/v1beta1/deployment_types.go!
# hack/bump-image-versions.sh can be used to update both.
images:
- name: k8s.gcr.io/sig-storage/csi-provisioner
  newTag: v2.2.1
- name: k8s.gcr.io/sig-storage/csi-node-driver-registrar
  newTag: v2.2.0

# Keep all the driver objects in 'pmem-csi' namespace
namespace: pmem-csi
