name: golangci-lint
on:
  push:
    tags:
      - "v*"
    branches:
      - "*"
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest

          # show only new issues if it's a pull request. The default value is `false`.
          # We still have issues in the existing code, but at least should not make it worse.
          only-new-issues: true

          args: --timeout=20m
