apiVersion: pmem-csi.intel.com/v1alpha1
kind: Deployment
metadata:
  name: example-deployment
spec:
  image: 172.17.0.1:5000/pmem-csi-driver:canary
  controllerResources:
      requests:
        cpu: "200m"
        memory: "100Mi"
  nodeResources:
      requests:
        cpu: "200m"
        memory: "100Mi"

